FROM quay.io/jupyter/scipy-notebook:2024-11-11

USER root

# Install utilities needed by the Jupyter + TPU environment.
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    curl \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

USER ${NB_UID}

COPY requirements.txt /tmp/requirements.txt

# Install python requirements
RUN pip install --no-cache-dir -r /tmp/requirements.txt
